version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: daily
      time: "03:00"
      timezone: Africa/Lusaka
    labels:
      - "dependencies"
    open-pull-requests-limit: 99
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: daily
      time: "03:00"
      timezone: Africa/Lusaka
    labels:
      - "dependencies"
    open-pull-requests-limit: 99
